modLoader = "kotlinforforge"
loaderVersion = "[${forge_kotlin_version},)"
issueTrackerURL = "${issue_tracker}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
displayURL = "${homepage}"
authors = ["${mod_author}"]
description = '''
${mod_description}
'''
logoFile = "logo.png"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.5,)"
ordering = "AFTER"