modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues"
license = "Apache-2.0"

[[mods]]
modId = "kubevs"
version = "${version}"
displayName = "KubeVS"
authors = ["TechTastic"]
description = '''
A KubeJS addon for VS2!
'''
logoFile = "assests/kubevs/logo.png"

[[dependencies.kubevs]]
modId = "forge"
mandatory = true
versionRange = "[40.1.69,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubevs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.kubevs]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubevs]]
modId = "architectury"
mandatory = true
versionRange = "[4.11.91,)"
ordering = "AFTER"
side = "BOTH"